### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by pautrull** [minghsu/usim_modifier_v3#6]
I have this error when i try to open usim_modifier.py
root@osboxes:/home/osboxes/usim_modifier_v3# ./usim_modifier.py 

Traceback (most recent call last):

  File "/home/osboxes/usim_modifier_v3/./usim_modifier.py", line 3, in <module>

    from control.controller import controller

  File "/home/osboxes/usim_modifier_v3/control/controller.py", line 4, in <module>

    from control.components import components

  File "/home/osboxes/usim_modifier_v3/control/components.py", line 5, in <module>

    from model.modeler import modeler

  File "/home/osboxes/usim_modifier_v3/model/modeler.py", line 4, in <module>

    from model.reader import reader

  File "/home/osboxes/usim_modifier_v3/model/reader.py", line 3, in <module>

    from smartcard.System import readers

ModuleNotFoundError: No module named 'smartcard'

Sorry, i'm new in Python and i don't know the way to fix it. 

Thanks a lot and sorry

**Comment by pautrull** [comment]
I fix it. Sorry
